// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZnEF_spF3fiNi0_8sD6iHgBeLzdshfU',
    appId: '1:991280352943:web:ccd10835ac6ebeeb844e5a',
    messagingSenderId: '991280352943',
    projectId: 'snm-solutions',
    authDomain: 'snm-solutions.firebaseapp.com',
    storageBucket: 'snm-solutions.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTzG6ylMsaU1Vo_L49CiUBoeMgqzytr_0',
    appId: '1:991280352943:android:2dd83d65dc679337844e5a',
    messagingSenderId: '991280352943',
    projectId: 'snm-solutions',
    storageBucket: 'snm-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1yGrisxwI0MecGuk03VHfbjvZVy1im2o',
    appId: '1:991280352943:ios:75ce9afd46604f55844e5a',
    messagingSenderId: '991280352943',
    projectId: 'snm-solutions',
    storageBucket: 'snm-solutions.firebasestorage.app',
    iosBundleId: 'com.example.crmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1yGrisxwI0MecGuk03VHfbjvZVy1im2o',
    appId: '1:991280352943:ios:75ce9afd46604f55844e5a',
    messagingSenderId: '991280352943',
    projectId: 'snm-solutions',
    storageBucket: 'snm-solutions.firebasestorage.app',
    iosBundleId: 'com.example.crmproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEZnEF_spF3fiNi0_8sD6iHgBeLzdshfU',
    appId: '1:991280352943:web:0dbd5fd23d5fa155844e5a',
    messagingSenderId: '991280352943',
    projectId: 'snm-solutions',
    authDomain: 'snm-solutions.firebaseapp.com',
    storageBucket: 'snm-solutions.firebasestorage.app',
  );

}