// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZPsgInyy_hebDsZ9vqSHQWAPRYaY4PHs',
    appId: '1:950913323152:web:84a2ef691a4f37b2ea4815',
    messagingSenderId: '950913323152',
    projectId: 'crmproject-821b6',
    authDomain: 'crmproject-821b6.firebaseapp.com',
    storageBucket: 'crmproject-821b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQVz8mNWXPRaugBunw7YBWr1_u05S5zYs',
    appId: '1:950913323152:android:dc623e1ed502fcf8ea4815',
    messagingSenderId: '950913323152',
    projectId: 'crmproject-821b6',
    storageBucket: 'crmproject-821b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGZPX36YvUUWA62Ja8v0Z4LKAGjH-ZbvE',
    appId: '1:950913323152:ios:71c3c0c8d14d5b7dea4815',
    messagingSenderId: '950913323152',
    projectId: 'crmproject-821b6',
    storageBucket: 'crmproject-821b6.firebasestorage.app',
    iosBundleId: 'com.example.crmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGZPX36YvUUWA62Ja8v0Z4LKAGjH-ZbvE',
    appId: '1:950913323152:ios:71c3c0c8d14d5b7dea4815',
    messagingSenderId: '950913323152',
    projectId: 'crmproject-821b6',
    storageBucket: 'crmproject-821b6.firebasestorage.app',
    iosBundleId: 'com.example.crmproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZPsgInyy_hebDsZ9vqSHQWAPRYaY4PHs',
    appId: '1:950913323152:web:c6ccec9b69bb738cea4815',
    messagingSenderId: '950913323152',
    projectId: 'crmproject-821b6',
    authDomain: 'crmproject-821b6.firebaseapp.com',
    storageBucket: 'crmproject-821b6.firebasestorage.app',
  );
}
